name: ccadmin-ui-build and deploy  

on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'app/**'
      - '.github/workflows/ui-shiftlog.yml'

env:
  APP_BASE_DIR: 'app'  
  NODE_VERSION: '16'
  APP_OUTPUT_DIR: 'app/dist'  
  
jobs:
  build-dev:
    if: ${{ github.ref == 'refs/heads/develop' }}  
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2 

      - name: Setup Node
        uses: actions/setup-node@v2 
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install packages'
        run: npm ci
        working-directory: ${{ env.APP_BASE_DIR }}
        
      - name: 'Build library'
        run: npm run build
        working-directory: ${{ env.APP_BASE_DIR }}
        
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEV_UI_AZURE_STAPP_PUBLISH_PROFILE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ${{ env.APP_OUTPUT_DIR }}
          api_location: ''
          output_location: ''
          skip_app_build: true
          routes_location: ${{ env.APP_BASE_DIR }}
  